site_name: DataPower Docs Base

docs_dir: .

site_dir: ../site

use_directory_urls: false

theme:
  name: material
  nav_style: nested

plugins:
  - search
  - monorepo
  - awesome-pages

nav:
  - Home: index.md
  - ...
