name: Datapower Docs Site

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    uses: ./.github/workflows/reusable-steps.yml
    steps:
    - name: Build MkDocs
      run: |
        mkdocs -v build -f ./datapower/mkdocs.yml

  deploy:
    needs: build
    uses: ./.github/workflows/reusable-steps.yml
    steps:
    - name: Deploy MkDocs site to GH pages
      run: |
        mkdocs -v gh-deploy -f ./datapower/mkdocs.yml